spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  liquibase:
    enabled: ${SPRING_LIQUIBASE_ENABLED:true}
    change-log: ${SPRING_LIQUIBASE_CHANGE_LOG:classpath:db/db.changelog-master.yaml}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true